services:
  api:
    image: brite_omdb
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/src/
    depends_on:
      - worker
    restart: always

  worker:
    image: brite_omdb
    container_name: worker
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: "./scripts/start_worker_dev"
    env_file: .env
    environment:
      - PORT=8090
    ports:
      - "8090:8090"
    volumes:
      - .:/src/
    depends_on:
      - pubsub
      - database
    restart: always

  database:
    image: postgres:13
    container_name: database
    env_file: .env
    ports:
      - "5432:5432"

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    container_name: pubsub
    env_file: .env
    ports:
      - "8585:8585"
    command: gcloud beta emulators pubsub start --project ${PUBSUB_PROJECT_ID} --host-port=0.0.0.0:8585
