class ErrorCode:
    AUTHENTICATION_REQUIRED = "Authentication required."
    AUTHORIZATION_FAILED = "Authorization failed. User has no access."
    INVALID_TOKEN = "Invalid token."
    INVALID_CREDENTIALS = "Invalid credentials."
    USERNAME_TAKEN = "Username is already taken."
    REFRESH_TOKEN_NOT_VALID = "Refresh token is not valid."
    REFRESH_TOKEN_REQUIRED = "Refresh token is required either in the body or cookie."
    USER_NOT_FOUND = "User not found."
    MOVIE_ALREADY_EXISTS = "Movie already exists."
    MOVIE_ALREADY_SUMBITTED = "Movie already submitted."
    MOVIE_NOT_FOUND = "Movie not found."